### ISSUE TITLE
macOS: Chromium crashes on launch

### ISSUE THREAD

**Issue by LukeChannings** [lucacasonato/deno-puppeteer#13]
```
deno 1.7.0 (release, x86_64-apple-darwin)
v8 8.9.255.3
typescript 4.1.3
```

I ran:

```
PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@5.5.1/install.ts
```

Which completed successfully.

I then tested the example:

```javascript
import puppeteer from "https://deno.land/x/puppeteer@5.5.1/mod.ts";

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto("https://example.com");
await page.screenshot({ path: "example.png" });

await browser.close();
```

But it throws an error:

```bash
λ deno run -A --unstable ./example.js
error: Uncaught (in promise) Error: Protocol error (Target.setDiscoverTargets): Target closed.
      this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                        ^
    at https://deno.land/x/puppeteer@5.5.1/vendor/puppeteer-core/puppeteer/common/Connection.js:69:57
    at new Promise (<anonymous>)
    at Connection.send (https://deno.land/x/puppeteer@5.5.1/vendor/puppeteer-core/puppeteer/common/Connection.js:68:12)
    at Function.create (https://deno.land/x/puppeteer@5.5.1/vendor/puppeteer-core/puppeteer/common/Browser.js:127:22)
    at ChromeLauncher.launch (Launcher.ts:113:37)
    at async file:///Users/luke/Desktop/example.js:3:17
```

**Comment by jonasgroendahl** [comment]
i get the same

**Comment by efraim-andrade** [comment]
same here on mac, i try on linux and works normally

**Comment by pmc-a** [comment]
I was getting the same, but was able to overcome it by specifying the actual path to my Chromium executable path within the `puppeteer.launch` arguments. Something like this:

```
const browser = await Puppeteer.launch({
    headless: true,
    executablePath: "/Applications/Chromium.app/Contents/MacOS/Chromium",
});
```

At a guess, I think this could be because the install cmd actually runs and installs the chromium within the Deno cache and deno-puppeteer is failing to launch it? Not entirely sure.

Hope this helps though!

**Comment by LukeChannings** [comment]
Good call @pmc-a,

I thought this was something to do with codesign or quarantine, but it turned out to be simpler than that.

Chromium has various helper apps in `Chromium.app/Contents/Frameworks/Chromium\ Framework.framework/Versions/<Current Version>/Helpers`, each of which need to be marked executable too.

I'm making a PR. In the meantime, you can fix this with:

```bash
chmod 755 ~/Library/Caches/deno/deno_puppeteer/chromium/*/chrome-mac/Chromium.app/Contents/Frameworks/Chromium\ Framework.framework/Versions/*/Helpers/*.app/Contents/MacOS/*
```

**Comment by felixsanz** [comment]
@LukeChannings @lucacasonato 

not fixed on linux, just got this on my first usage

**Comment by caperaven** [comment]
I am also getting this issue on windows.
Is there a solution for this yet.
