### ISSUE TITLE
Bad resource ID when closing browser

### ISSUE THREAD

**Issue by ddorstijn** [lucacasonato/deno-puppeteer#17]
Running both the scripts in the examples given in the readme I get the following error:

error: Uncaught (in promise) BadResource: Bad resource ID
    at processResponse (deno:core/core.js:212:11)
    at jsonOpSync (deno:core/core.js:236:12)
    at Object.close (deno:core/core.js:252:5)
    at WebSocket.#eventLoop (deno:op_crates/websocket/01_websocket.js:368:18)

For this example the following code was used but the error is given every time I run the `await browser.close()` command.

``` typescript
import puppeteer from "https://deno.land/x/puppeteer@5.5.1/mod.ts";

const browser = await puppeteer.launch();
const page = await browser.newPage();
await page.goto("https://example.com");
await page.screenshot({ path: "example.png" });

await browser.close();
```

The screenshot does get saved so the problem really seems to be once puppeteer is finished.

**Comment by lucacasonato** [comment]
Issue should now be resolved in Deno 1.9.2.
