### ISSUE TITLE
Support args option in chrome options

### ISSUE THREAD

**Issue by cryptogohan** [lucacasonato/deno-puppeteer#24]
My options look as follows:
```ts
const browser = await launch({
  executablePath: "/usr/bin/chromium-browser",
  args: [
    // Required for Docker version of Puppeteer
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--headless",
    "--disable-gpu",
    // This will write shared memory files into /tmp instead of /dev/shm,
    // because Docker’s default for /dev/shm is 64MB
    "--disable-dev-shm-usage",
  ],
});
```

Bit of a mess to be able to run in Docker with alpine. There may be a better option that I'd be open to haha. Regardless, it seems puppeteer is happy with these options and runs well. However, the types don't support this giving me a false positive type error. I'm guessing it's ChromeOptions that needs to be a bit more flexible? Not sure. What do you think?

Thanks for this great module!

**Comment by lucacasonato** [comment]
What exactly is the issue? `executablePath` and `args` arguments in the `ChromeOptions` option bag  works for me. Do you have a specific TS error code?

**Comment by cryptogohan** [comment]
Strange, removed the `any` type assertion, no more error. Maybe it had to do with how I was importing `launch` directly. Using this now:

```ts
const browser = await puppeteer.launch({
  executablePath: Deno.env.get("CHROME_PATH")!,
  args: [
    // Required for Docker version of Puppeteer
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--headless",
    "--disable-gpu",
    // This will write shared memory files into /tmp instead of /dev/shm,
    // because Docker’s default for /dev/shm is 64MB
    "--disable-dev-shm-usage",
  ],
});
```

Thanks for the reply! Removes a `as any` from my code 😄 .
