### ISSUE TITLE
pdf binary contents

### ISSUE THREAD

**Issue by cherepanov** [lucacasonato/deno-puppeteer#27]
I'm trying to grab binary pdf contents.
Writing to file works fine.
In node pdf() returns ```Promise<Buffer>```.
In deno promise always resolves to ```Uint8Array(2) [ 0, 0 ]```
Can't get how to make work.
Any piece of advice?

**Comment by johannschopplich** [comment]
Running into the same issues myself. The output of the `.pdf()` method will always return the same content.

**Comment by cherepanov** [comment]
Probably issue cause somewhere around this line, as of file written correctly.
 I'm very new to deno and pptr, have no idea what this function should do.

https://github.com/lucacasonato/deno-puppeteer/blob/74f1e21845f7ded5e2408ce72b4765cd20f016ca/vendor/puppeteer-core/puppeteer/common/helper.js#L269

**Comment by lucacasonato** [comment]
Fixed by #31
