### ISSUE TITLE
`ReferenceError` when calling HTTPResponse's `arrayBuffer()` method.

### ISSUE THREAD

**Issue by c0per** [lucacasonato/deno-puppeteer#40]
When you want to get the arrayBuffer of a response body, `res.arrayBuffer()` throws a ReferenceError.

```ts
page.on("response", (res) => {
    res.arrayBuffer();
});

---
error: Uncaught (in promise) ReferenceError: base64Decode is not defined
        return response.base64Encoded
```

**Comment by c0per** [comment]
It turns out to be a simple mistake. It's just a function needs to be imported. I'll send a PR to fix this.

**Comment by felixsanz** [comment]
@lucacasonato can this be fixed please? thanks!

**Comment by lucacasonato** [comment]
Feel free to contribute a PR!

**Comment by felixsanz** [comment]
> Feel free to contribute a PR!

done! xd

![1650630611](https://user-images.githubusercontent.com/6182099/164714673-97d82922-1283-4d5d-981f-9ae51d696661.jpg)
