### ISSUE TITLE
Error: JSHandle#uploadFile can only be used in Node-like environments on deno-puppeteer-16.2.0

### ISSUE THREAD

**Issue by cavoirom** [lucacasonato/deno-puppeteer#62]
Hello, thank you for your effort in this project.

I could use puppeteer on v14.1.1, I recently update the library to v16.2.0 and found that the upload is not working. When click on the browse button, an error happen:

```
error: Uncaught (in promise) Error: JSHandle#uploadFile can only be used in Node-like environments.
        throw new Error(
              ^
    at ElementHandle.uploadFile (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/ElementHandle.js:668:15)
    at async FileChooser.accept (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/FileChooser.js:122:5)
```

Deno:

```
$ deno --version                                                                                               
deno 1.25.2 (release, x86_64-apple-darwin)
v8 10.6.194.5
typescript 4.7.4
```

**Comment by ttschnz** [comment]
same here:
```
deno 1.29.1 (release, x86_64-pc-windows-msvc)
v8 10.9.194.5
typescript 4.9.4
```

**Comment by ttschnz** [comment]
it seems like the `uploadFile` function depends on nodes `path` library. Maybe this could be replaced with Denos builtin functions?

https://github.com/lucacasonato/deno-puppeteer/blob/45b3162585b98ad8d54abeb56f48ecbb17c614eb/vendor/puppeteer-core/puppeteer/common/ElementHandle.js#L665

**Comment by cavoirom** [comment]
@ttschnz yes, we could use `node:` specifier for this case.

**Comment by devingfx** [comment]
Hi, thx pointing out this...
A workaround that is working until PR is merged: 
is to set this in `deno.json`'s imports:
```json
        "imports": {
		"path": "node:path",
		"fs": "node:fs",
		"puppeteer": "https://deno.land/x/puppeteer@16.2.0/mod.ts"
	}
```

**Comment by cavoirom** [comment]
For future reader. This project seem outdated and you probably don't need it. Just use `puppeteer-core` package from npm with npm specifier, for example: `npm:puppeteer-core@21.7.0`. I tested it and it work as expected. This is possible because Deno recently improves the compatibility with Node/npm a lot.
