### ISSUE TITLE
How to use it with browserless.io?

### ISSUE THREAD

**Issue by caffo** [lucacasonato/deno-puppeteer#66]
Can I override the local browser check? I'm using the following:

```
const getBrowser = async function () {
    puppeteer.connect({ browserWSEndpoint: 'wss://chrome.browserless.io?token=[REDACTED] })
    puppeteer.launch();
```

And I'm still getting the `browser not found` error.

```
error: Uncaught Error: Could not find browser revision 1022525. Run "PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts" to download a supported browser binary.
```

The entire point of using browserless is to not require a local browser installation 😊

**Comment by vibegui** [comment]
I've updated Luca's example and it's working here: https://github.com/guifromrio/puppeteer_on_deploy/blob/main/main.tsx

**Comment by caffo** [comment]
Thanks!
